source "https://rubygems.org"

  gem 'sinatra'
  gem 'capybara'
  gem 'cucumber'
  gem 'cucumber-sinatra'
  gem 'launchy'
  gem 'rspec'
  gem 'shotgun'
  gem 'byebug'
  gem 'data_mapper'
  gem 'dm-postgres-adapter'
  gem 'database_cleaner'
  gem 'bcrypt-ruby'
  gem 'rack-flash3'
  gem 'sass'
  gem 'pony'
  gem 'pg'